# Generated by Django 5.2.9 on 2025-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Profile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
