# Generated by Django 5.2.9 on 2025-12-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_appointment_created_at_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
