# Generated by Django 5.2.9 on 2025-12-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
